# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sign_up_dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("sign_up_dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(400, 164)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.username_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_lineedit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_lineedit.setFont(font)
        self.username_lineedit.setObjectName("username_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_lineedit)
        self.password_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_lineedit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_lineedit.setFont(font)
        self.password_lineedit.setObjectName("password_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_lineedit)
        self.repeat_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.repeat_label.setFont(font)
        self.repeat_label.setObjectName("repeat_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.repeat_label)
        self.repeat_lineedit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.repeat_lineedit.setFont(font)
        self.repeat_lineedit.setObjectName("repeat_lineedit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.repeat_lineedit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username_lineedit, self.password_lineedit)
        Dialog.setTabOrder(self.password_lineedit, self.repeat_lineedit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sign up"))
        self.username_label.setText(_translate("Dialog", "Username:"))
        self.password_label.setText(_translate("Dialog", "Password:"))
        self.repeat_label.setText(_translate("Dialog", "Repeat:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_sign_up_dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
